---
kind: Namespace
apiVersion: v1
metadata:
  name: minecraft
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-claim
  namespace: minecraft
spec:
  accessModes:
    - ReadOnlyMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "do-block-storage"
---
# kind: ServiceAccount
# apiVersion: v1
# metadata:
#   name: minecraft-server-controller
#   namespace: minecraft
---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: minecraft-server-controller
  namespace: minecraft
  labels:
    application: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      application: minecraft
  template:
    metadata:
      labels:
        name: minecraft-server
        application: minecraft
    spec:
      # serviceAccountName: minecraft-server-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: ilix/minecraft
        name: minecraft-server
        ports:
        - name: server
          containerPort: 25565
          hostPort: 25565
        # securityContext:
        #   capabilities:
        #     drop:
        #     - ALL
        #     add:
        #     - NET_BIND_SERVICE
        volumeMounts:
        - name: minecraft
          mountPath: /mc
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: minecraft-server-claim
---
# kind: Service
# apiVersion: v1
# metadata:
#   name: minecraft-server-service
#   namespace: minecraft
# spec:
#   selector:
#     application: minecraft
#   ports:
#     - protocol: TCP
#       port: 25565
#       name: server
