---
kind: Namespace
apiVersion: v1
metadata:
  name: minecraft
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: server-claim
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "do-block-storage"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: map-claim
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: "do-block-storage"
---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    application: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      application: minecraft
  template:
    metadata:
      labels:
        name: minecraft-server
        application: minecraft
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: ilix/minecraft
        name: minecraft-server
        ports:
        - name: server
          containerPort: 25565
          hostPort: 25565
        volumeMounts:
        - name: minecraft
          mountPath: /mc
          readOnly: false
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: server-claim
---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: minecraft-overviewer
  namespace: minecraft
  labels:
    application: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      application: minecraft
  template:
    metadata:
      labels:
        name: minecraft-overviewer
        application: minecraft
    spec:
      containers:
      - image: ilix/minecraft-overviewer:v0.1.2
        name: minecraft-overviewer
        volumeMounts:
        - name: minecraft
          mountPath: /mc
          readOnly: true
        - name: map
          mountPath: /map
          readOnly: false
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: server-claim
        - name: map
          persistentVolumeClaim:
            claimName: map-claim
---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: minecraft-nginx
  namespace: minecraft
  labels:
    application: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      application: minecraft
  template:
    metadata:
      labels:
        name: minecraft-nginx
        application: minecraft
    spec:
      containers:
      - image: nginx
        name: minecraft-nginx
        ports:
        - name: nginx
          containerPort: 80
          hostPort: 8080
        volumeMounts:
        - name: map
          mountPath: /usr/share/nginx/html
          readOnly: true
      volumes:
        - name: map
          persistentVolumeClaim:
            claimName: map-claim
