---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minecraft-server-controller
  namespace: minecraft
---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: minecraft-server-controller
  namespace: minecraft
  labels:
    k8s-app: minecraft
spec:
  template:
    metadata:
      labels:
        k8s-app: minecraft
        name: minecraft-server
    spec:
      serviceAccountName: minecraft-server-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: ilix/minecraft
        name: minecraft-server
        ports:
        - name: server
          containerPort: 25565
          hostPort: 25565
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
---
kind: Service
apiVersion: v1
metadata:
  name: minecraft-server-service
  namespace: minecraft
spec:
  selector:
    k8s-app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      name: server
